# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUI():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_uI(self):
    self.driver.get("http://ffls-frontend-app-bucket-prod.s3-website-us-east-1.amazonaws.com/")
    self.driver.set_window_size(652, 672)
    self.driver.find_element(By.LINK_TEXT, "What\'s next?").click()
    self.driver.find_element(By.CSS_SELECTOR, "details:nth-child(3) > summary").click()
    self.driver.find_element(By.CSS_SELECTOR, "details:nth-child(4) > summary").click()
    self.driver.find_element(By.CSS_SELECTOR, "details:nth-child(5) > summary").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".list-item-link:nth-child(5) > span").click()
    self.vars["win5471"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win5471"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".list-item-link:nth-child(2) > span > span").click()
    self.vars["win9931"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9931"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".list-item-link:nth-child(4) > span").click()
    self.vars["win6229"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6229"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "nx-console").click()
    self.vars["win5708"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win5708"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.close()
  
