name: Build and Upload to AWS S3 Bucket

on:
  push:
    branches:
      - main
      - staging
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Determinar el ambiente en base a la rama
      - name: Determine Environment
        id: env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "bucket=${{ vars.AWS_S3_BUCKET_PROD }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "bucket=${{ vars.AWS_S3_BUCKET_QA }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "development" ]]; then
            echo "bucket=${{ vars.AWS_S3_BUCKET_DEV }}" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '22'
            cache: 'npm'

      - name: Update npm
        run: npm install -g npm@10

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: build/
          AWS_S3_BUCKET: ${{ env.bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: ${{ env.bucket }}