name: Build and Upload to AWS S3 Bucket

on:
  push:
    branches:
      - main
      - staging
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Determinar el ambiente en base a la rama
      - name: Determine Environment
        id: env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "bucket=${{ vars.AWS_S3_BUCKET_PROD }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "bucket=${{ vars.AWS_S3_BUCKET_QA }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "development" ]]; then
            echo "bucket=${{ vars.AWS_S3_BUCKET_DEV }}" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '22'
            cache: 'npm'

      - name: Update npm
        run: npm install -g npm@10

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
         aws-region: "us-east-1"

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync dist/apps/catalog s3://${{ env.bucket }}
        env:
          bucket: ${{ env.bucket }} 